#!/usr/bin/env bash
# Script to make an nginx server listen on port 80
sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
