#!/usr/bin/env bash
# Makes sure:
#+ nginx is running as user nginx
#+ nginx must be listening on all active IP on port 8080
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill apache2
chmod 644 /etc/nginx/nginx.conf
sudo --user nginx service nginx start
